### ISSUE TITLE
search navigation: legacy and back

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1896]
Testing #1890. Starting in legacy recording layout and going elsewhere through the search. 

Started in AA. Searched for LA. Already an issue: 

<img width="1027" alt="Screen Shot 2022-10-25 at 8 10 50 AM" src="https://user-images.githubusercontent.com/67970402/197781946-481fb8e7-8d65-4812-8349-0ba94d53d62f.png">

Going back from LA to AA through both layout history and recently viewed worked fine.

**Comment by urapadmin** [comment]
### 13.6.12
this should work now

**Comment by luizaogs** [comment]
Hmm this one is still not working. Searching for LA in the AA layout still gives me this: 

<img width="1019" alt="Screen Shot 2022-10-27 at 8 18 16 AM" src="https://user-images.githubusercontent.com/67970402/198295200-7218a24b-79a0-4506-b4e2-b70dddd133c4.png">

**Comment by urapadmin** [comment]
argl. This will never end. You must already have nightmares from it :(On 27. Oct 2022, at 15:18, luizaogs ***@***.***> wrote:﻿
Hmm this one is still not working. Searching for LA in the AA layout still gives me this:

**Comment by urapadmin** [comment]
I am glad to hear :/

**Comment by urapadmin** [comment]
(FYI: @lbestock) For technical reasons (it is simpler) but also I think for usability reasons I am okay with the fact that searching does add the target to the navigation history even if the target does not required the layout to change. But it does lead to the confusing situation that you are in LA, search for LA and go back to LA.

**Comment by urapadmin** [comment]
### 13.6.13
I really hope that's fixed now.

**Comment by luizaogs** [comment]
'Tis.
