### ISSUE TITLE
kiosk harris matrix: zoom to fit request

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2515]
Playing in the Harris Matrix with different colored backgrounds. Appreciating the "contemporary relations" (except on the white background, where I cannot see it easily).

How hard would it be to make it possible to zoom to fit? I can't get all of URAP unit FA on my screen and not only does that make it harder to read for information, I also then keep scrolling left and right and accidentally going back to the previous page, and then going forward again doesn't take me back to the HM but only to the HM lab where I have to search again for FA.

**Comment by lbestock** [comment]
(Also just noted, in #2399 there is a contemporary relation between FA-019 and FA-003. That is not present in the HM generated now in URAP. Why?)

**Comment by urapadmin** [comment]
> (Also just noted, in #2399 there is a contemporary relation between FA-019 and FA-003. That is not present in the HM generated now in URAP. Why?)
> 
> (Ah, that is an "adjacent to" relation and I think you changed the implications of that? At least, it is proper now that it not register as a contemporary relation.)

You are making a mess. This has nothing to do with the headline. If there is a contemporary relation depends entirely on the temporal type of the relation. Adjacent to is spatial. It should depend on a project's configuration whether or not "adjacent to" is "same time as" or not. That is at least how it should work. So please check and if it does not behave correctly, please make a new ticket.

**Comment by urapadmin** [comment]
as I just explained to Luiza in #2518, this is a Lab project that we use to test the Harris Matrix component it self, so the thing that draws. That's why the user interface around the component is as basic as it gets. But you can use your browser's zoom for now. 

Later it is planned to have a proper zooming and presumably panning (moving the thing around with the mouse instead of the scroll-bars). And then it should be possible to also have a button that switches between zoom to fit and original scale. 
So, yes, definitely on the list.

**Comment by lbestock** [comment]
Bloody Chrome on the Mac does not allow me to zoom out, only in. I cannot use the browser to see the whole thing. But I will be patient.

**Comment by urapadmin** [comment]
### plugin 0.6
- this exists now. It is the "collapse" button second from the right. More on zooming see #2535

**Comment by urapadmin** [comment]
Not working on iOS.

**Comment by urapadmin** [comment]
not working in FireFox. So something is wrong.

**Comment by urapadmin** [comment]
💤

**Comment by luizaogs** [comment]
Yeah, not working in Chrome either.

**Comment by urapadmin** [comment]
### plugin 0.7
- should be working now

**Comment by luizaogs** [comment]
Should this only zoom to fit horizontally? Vertically FA still does not all fit after pressing the button.

**Comment by luizaogs** [comment]
Then this is good.

**Comment by urapadmin** [comment]
not working anymore because of:
