### ISSUE TITLE
Q&V: Dayplans not showing text and record properly if image is missing

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2710]
Ok, the relations part is fine.

BUT I have image containers showing up in LA in Q&V that exist in the recording as image containers and not images. Is that right still? Or should there just be nothing? 

This is what it looks like: 

<img width="1512" alt="Screenshot 2024-05-15 at 8 02 34 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/9a041f7f-1924-477e-8fdd-73719b5baece">

<img width="1027" alt="Screenshot 2024-05-15 at 8 02 46 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/3302671d-3b93-4556-9e88-a5fd98417dc5">

_Originally posted by @luizaogs in https://github.com/arch-kiosk/arch-kiosk-office/issues/2392#issuecomment-2112798113_

**Comment by urapadmin** [comment]
You actually have a dayplan record (even some text with it) but not an image. So the absent image container is fine (there is none, that's why the layout looks bad there) but I would want to see the dayplan text and the layout should deal with the missing container better.

**Comment by urapadmin** [comment]
### Kiosk 1.6.24
- this should be fixed now due to #2875

**Comment by luizaogs** [comment]
I still don't see the dayplan text for this. I'm not sure if this is what you intended because you didn't mention descriptions in your solution for #2875

**Comment by urapadmin** [comment]
the description should show and instead of a blank container it was meant to be a tentaculair. Might still not be working. What is your example?

**Comment by luizaogs** [comment]
The tentaculaire worked but not the description. The example is the same one as above: in LA, it's the image added on 7.XI.2022 at 9:48pm.

**Comment by luizaogs** [comment]
Forgot to include a screenshot yesterday in case it helps you find it (this is in the third row of LA photos): 

<img width="818" alt="Image" src="https://github.com/user-attachments/assets/eb44680a-7583-4a02-9837-c41af6c5bcfd" />

**Comment by urapadmin** [comment]
ja, this is still not okay. The text should be 'Ok I wanted to add the photo of a chicken but Apple is being veeeery weird right now' and the dayplan's uid is `08dc1337-a8fa-4578-8301-f2d6aed23ae8` Note that this is a version where the dayplan's uid_image is actually null, so that's not really a broken image, it is an empty image container.

**Comment by luizaogs** [comment]
🐓🐣 (don't ask me what chicken I was talking about)

**Comment by urapadmin** [comment]
I won't 🐔

**Comment by luizaogs** [comment]
No, I'll tell you. They were some crazy looking chickens in Monet's garden in Giverny. If you're in need of a smile I highly recommend looking up Padua chickens.

**Comment by urapadmin** [comment]
I will. I have a sweet spot for chicken because I once lived for a while on a (glamping-style) farm and my companions were white Orpingtons. Hilarious beasts. And super fluffy.

**Comment by urapadmin** [comment]
ha, they somehow look very Louis XIV to me

**Comment by luizaogs** [comment]
I would totally hug an Orpington (not sure it would go very well for me)

**Comment by urapadmin** [comment]
they are very friendly and even want to huddle nearby but they are also veeery dirty around the bum 💩

**Comment by luizaogs** [comment]
Ah yes well, fortunately (unfortunately?) I have had some practice on that front 🐈🐈🐈

**Comment by urapadmin** [comment]
turning from chicken to the less pleasant issue at hand: It is really #2875 reloaded. I have been here already and the problem cannot be solved easily. If the container is blank there is no image and hence no uid for an image.. And so I have no handle on the file's accumulated description. But here I am showing an accumulated description - as always in a Q&V gallery. Because there is no uid the thing does not show up in the file repository at all. This is different from a broken image, which has a uid and so I do have a handle on the accumulated descriptions. 

This cannot easily be solved, so I postpone it to a more major iteration of Q&V development. It is in the end not a very common or reasonable recording result, I hope.
